version: 2

jobs:
  build:
    docker:
      - image: "node:dubnium"
    steps:
      - checkout:
      - attach_workspace:
          at: .
      - run:
          name: Install node dependencies
          command: npm install
      - run:
          name: Build production
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: "coxauto/aws-ebcli"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Checking eb cli tool"
          command: "eb --version"
      - run:
          name: "Checking source code configuration"
          command: "ls"
      - run:
          name: "Deploy to Beanstalk"
          command: "eb deploy"
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

